# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(297, 424)
        Form.setWindowTitle("sdfsdf")
        self.pushButton0 = QtWidgets.QPushButton(Form)
        self.pushButton0.setGeometry(QtCore.QRect(10, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton0.setFont(font)
        self.pushButton0.setStyleSheet("QPushButton{\n"
                                       "color: black;\n"
                                       "background-color: rgb(115, 115, 115) ;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "background: silver;\n"
                                       "transition: 1s;\n"
                                       "}")
        self.pushButton0.setObjectName("pushButton0")
        self.pushButton_equals = QtWidgets.QPushButton(Form)
        self.pushButton_equals.setGeometry(QtCore.QRect(220, 350, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("QPushButton{\n"
                                             "color: black;\n"
                                             "background-color:  rgb(232, 143, 19);\n"
                                             "\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "background: rgb(231, 231, 231);\n"
                                             "transition: 1s;\n"
                                             "}")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.pushButton_point = QtWidgets.QPushButton(Form)
        self.pushButton_point.setGeometry(QtCore.QRect(150, 350, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_point.setFont(font)
        self.pushButton_point.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_point.setStyleSheet("QPushButton{\n"
                                            "color: black;\n"
                                            "background-color: rgb(115, 115, 115) ;\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "background: silver;\n"
                                            "transition: 1s;\n"
                                            "}")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_plus = QtWidgets.QPushButton(Form)
        self.pushButton_plus.setGeometry(QtCore.QRect(220, 290, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("QPushButton{\n"
                                           "color: black;\n"
                                           "background-color:  rgb(232, 143, 19);\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "background: rgb(231, 231, 231);\n"
                                           "transition: 1s;\n"
                                           "}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setGeometry(QtCore.QRect(220, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("QPushButton{\n"
                                            "color: black;\n"
                                            "background-color:  rgb(232, 143, 19);\n"
                                            "\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "background: rgb(231, 231, 231);\n"
                                            "transition: 1s;\n"
                                            "}")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_multiply = QtWidgets.QPushButton(Form)
        self.pushButton_multiply.setGeometry(QtCore.QRect(220, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("QPushButton{\n"
                                               "color: black;\n"
                                               "background-color:  rgb(232, 143, 19);\n"
                                               "\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "background: rgb(231, 231, 231);\n"
                                               "transition: 1s;\n"
                                               "}")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.pushButton_division = QtWidgets.QPushButton(Form)
        self.pushButton_division.setGeometry(QtCore.QRect(220, 110, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_division.setFont(font)
        self.pushButton_division.setStyleSheet("QPushButton{\n"
                                               "color: black;\n"
                                               "background-color:  rgb(232, 143, 19);\n"
                                               "\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "background: rgb(231, 231, 231);\n"
                                               "transition: 1s;\n"
                                               "}")
        self.pushButton_division.setObjectName("pushButton_division")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 290, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 290, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 290, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "color: black;\n"
                                        "background-color: rgb(115, 115, 115) ;\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: silver;\n"
                                        "transition: 1s;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_percent = QtWidgets.QPushButton(Form)
        self.pushButton_percent.setGeometry(QtCore.QRect(150, 110, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("QPushButton{\n"
                                              "color: black;\n"
                                              "background-color:rgb(200,200,200);\n"
                                              "\n"
                                              "\n"
                                              "\n"
                                              "\n"
                                              "\n"
                                              "}\n"
                                              "\n"
                                              "\n"
                                              "QPushButton:hover {\n"
                                              "background: silver;\n"
                                              "transition: 1s;\n"
                                              "}")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_change = QtWidgets.QPushButton(Form)
        self.pushButton_change.setGeometry(QtCore.QRect(80, 110, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_change.setFont(font)
        self.pushButton_change.setStyleSheet("QPushButton{\n"
                                             "color: black;\n"
                                             "background-color:rgb(200,200,200);\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "background: silver;\n"
                                             "transition: 1s;\n"
                                             "}")
        self.pushButton_change.setObjectName("pushButton_change")
        self.pushButton_delete = QtWidgets.QPushButton(Form)
        self.pushButton_delete.setGeometry(QtCore.QRect(10, 110, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton{\n"
                                             "color: black;\n"
                                             "background-color:rgb(200,200,200);\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "background: silver;\n"
                                             "transition: 1s;\n"
                                             "}")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label = QtWidgets.QLabel(Form)
        self.label.setWordWrap(True)
        self.label.setGeometry(QtCore.QRect(11, 10, 279, 94))

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.add_function()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Калькулятор"))
        self.pushButton0.setText(_translate("Form", "0"))
        self.pushButton_equals.setText(_translate("Form", "="))
        self.pushButton_point.setText(_translate("Form", "."))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_multiply.setText(_translate("Form", "*"))
        self.pushButton_division.setText(_translate("Form", "/"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_percent.setText(_translate("Form", "%"))
        self.pushButton_change.setText(_translate("Form", "+/-"))
        self.pushButton_delete.setText(_translate("Form", "AC"))

    def add_function(self):
        self.pushButton0.clicked.connect(
            lambda: self.write_function(self.pushButton0.text()))
        self.pushButton_1.clicked.connect(
            lambda: self.write_function(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(
            lambda: self.write_function(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(
            lambda: self.write_function(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(
            lambda: self.write_function(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(
            lambda: self.write_function(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(
            lambda: self.write_function(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(
            lambda: self.write_function(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(
            lambda: self.write_function(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(
            lambda: self.write_function(self.pushButton_9.text()))
        self.pushButton_equals.clicked.connect(self.result)
        self.pushButton_point.clicked.connect(
            lambda: self.write_function(self.pushButton_point.text()))
        self.pushButton_plus.clicked.connect(
            lambda: self.write_function(self.pushButton_plus.text()))
        self.pushButton_minus.clicked.connect(
            lambda: self.write_function(self.pushButton_minus.text()))
        self.pushButton_multiply.clicked.connect(
            lambda: self.write_function(self.pushButton_multiply.text()))
        self.pushButton_division.clicked.connect(
            lambda: self.write_function(self.pushButton_division.text()))
        self.pushButton_percent.clicked.connect(self.percent_function)
        self.pushButton_change.clicked.connect(self.change_function)
        self.pushButton_delete.clicked.connect(
            lambda: self.delete_function(self.pushButton_delete.text()))

    def write_function(self, num):
        if self.label.text() == "0":
            self.label.setText(num)
        else:
            self.label.setText(self.label.text() + num)

    def delete_function(self, text):
        self.label.setText("0")

    def result(self):
        no_correct = ""
        for i in self.label.text():
            no_correct += i
        try:
            "/0" in no_correct
            res = eval(self.label.text())
            self.label.setText(str(res))
        except:
            self.label.setText("Ошибка")

    def percent_function(self, text):
        while True:
            if self.label.text() != "0":
                self.label.setText(str(float(self.label.text()) / 100))
                break
            else:
                self.label.setText("0")
                break

    def change_function(self, text):
        while True:
            if float(self.label.text()) == 0.0:
                self.label.setText("0")
                break
            if float(self.label.text()) > 0.0:
                self.label.setText("-" + self.label.text())
                break
            if float(self.label.text()) < 0.0:
                self.label.setText(self.label.text()[1:])
                break
